
all:
	go run github.com/gokrazy/tools/cmd/gokr-packer \
		-overwrite=test.img -target_storage_bytes=1200000000 \
		-kernel_package github.com/anisse/beatbox-kernel \
		-hostname beatbox \
		github.com/anisse/beatbox
